{
 "title": "Logs & Correlation",
 "tags": [
  "logs",
  "loki",
  "gym"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Backend Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"containerlogs\"} |= \"backend\""
    }
   ]
  },
  {
   "title": "Logs par conteneur",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"containerlogs\"} |= \"backend\" [1m])) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Erreurs detectees",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"containerlogs\"} |~ \"(?i)error\" [1m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Tous les logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{job=\"containerlogs\"}"
    }
   ]
  }
 ]
}